### PR TITLE
s=-1 source added

### PR DESCRIPTION
**Pull request by TheoTorresV**
ConvolveSource.m, TeukolskyMode.m and TeuksolskySource.m were modified to incorporate the s=-1 case to the flux calculation.
Only includes equatorial and circular orbits.

test_EMsource is a notebook to compare the flux calculation to the dissipative self-force evaluated at the particle.

### CODE REVIEW

**Comment by nielsw2** [comment]
I had a look at this and couldn't find any issues. The comparison with the local dissipative force is very convincing as well. Do you know if the values for the flux for circular orbits in Schwarzschild or Kerr are tabulated somewhere in the literature? This could be useful as an independent check that we could use for a unit test.

**Comment by barrywardell** [comment]
This is a great addition. I just have two bigger comments/questions and a few pedantic ones:
- Can you explain why you need to use the TS identities and the s=+1 solutions for the s=-1 case?
- How hard would it be to implement the s=+1 case also?
- For some reason the git diffs are indicating all lines have changed, but that doesn't seem to be the case. It may just be a matter of whitespace (e.g. line endings) changes. It would be good if those didn't appear in the commit.
- Similarly, a number of the Sections have changed from Closed to open. This clutters the diffs, making them a bit harder to read

**Comment by TheoTorresV** [comment]
Sorry for the late reply.

@nielsw2 
- Regarding the tabulation of data: I am not aware of any paper tabulating the data for fluxes either in the Scharzschild or Kerr case. There is a paper by Roland Haas (https://arxiv.org/abs/1112.3707) where the radial component of the electromagnetic self-force is plotted. We have reproduced this plot and our data are in agreement with Roland's paper. This is the only comparison with the literature we have been able to do so far. I will continue to look for some explicit values.

@barrywardell I am not quite sure what you mean by s = -1 case compared to s=+1.
- I use the TS identities because I need to reconstruct 2 Maxwell scalars: phi_0 and phi_2. to compute the flux at infinity and at the horizon. phi_0 which is given by R_{+1} gives the flux at the horizon and phi_2 by which is given by R_{-1} gives the flux at infinity. Instead of using TeukolskyRadial to compute R_{+1} and R_{-1}, I thought it would be faster to use TeukolskyRadial only once and then get the other spin via the TS identities.
- Could you explain what do you mean by the s=+1 case? Do you mean to compute everything using only the +1 radial function instead of the -1?
- I am relatively new to git and I don't understand why the git diffs are indicated that all lines have changed. I have simply added my part in the middle of the original code without touching the rest. I will have a look at this for the final commit.

We are currently writing up the paper with Sam Dolan to present our result. We could wait to have the paper out to double check everything and make sure everything agrees.

**Comment by barrywardell** [comment]
@TheoTorresV: Thanks for the explanations.

- I've tidied up the whitespace and problem with the diffs. It was most likely caused by your editor (I guess you're using Windows?).
- I mean it would be great to also be able to construct the solution for the s=+1 scalar (corresponding to \phi_0, rather than \phi_2). We don't yet have that for s=+2 though, so it's not a major priority.
- I understand now why you have used the TS identities (to get the flux through the horizon). I think this is best moved to the flux calculation, as in the s=-2 case.  This should be a matter of including an appropriate factor, similar to the factor of \alpha in the s=-2 case. The appropriate factor comes from using the TS identity to determine how the asymptotic amplitudes for the s=+1 solutions are related to the s=-1 solutions. I think this might already be worked out in Ori's paper.

**Comment by barrywardell** [comment]
Commit 4c32d92 implements my last point.

**Pull request merged**
